# Generated by Django 5.1.3 on 2025-02-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_cart_created_at_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Order Placed', max_length=100),
        ),
    ]
