# Generated by Django 5.1.6 on 2025-03-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
